plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*.rake'
    - 'Rakefile'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'lib/tasks/**/*.rake'
