when:
  event:
    - push
    - pull_request

steps:
  root_quality:
    image: python:3.12-slim
    commands:
      - pip install uv
      - uv sync
      - uv run ruff check .
      - uv run ruff format --check .
      - uv run mypy scripts
      - uv run doctor
