when:
  event:
    - push
    - pull_request

steps:
  root_quality:
    image: ruby:3.3-slim
    commands:
      - gem install bundler
      - bundle install
      - bundle exec rubocop
      - bundle exec rake scry:doctor
